spring:
    datasource:
        password: H3fadmin
        url: jdbc:sqlserver://ecm-tienhuynh-tn.database.windows.net:1433;database=ECM;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
        username: ecm-sa@ecm-tienhuynh-tn

# jdbc:sqlserver://ecm-tienhuynh-tn.database.windows.net:1433;database=ECM;user=ecm-sa@ecm-tienhuynh-tn;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

logging:
    level:
        root: info
        com.happy3friends.toiletmapbackend.service: error
    file:
        path: logs
        name: ${logging.file.path}/mylog.log
    pattern:
        file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level [%t] [%c{1}] %logger{0}.%M:%line - %msg%n"
        console: "%highlight([%-5level]):%yellow([%d{yyyy-MM-dd HH:mm:ss.SSS}])[%blue(%t)]%cyan([%c{1}]):[%green(%line)]:%boldMagenta(%X{path}) - %m %n"