spring:
    datasource:
        password: H3fadmin
        url: jdbc:sqlserver://ecm-tienhuynh-tn.database.windows.net:1433;database=ECM;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
        username: ecm-sa@ecm-tienhuynh-tn

# jdbc:sqlserver://ecm-tienhuynh-tn.database.windows.net:1433;database=ECM;user=ecm-sa@ecm-tienhuynh-tn;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

#app:
#    oauth2:
#        # After successfully authenticating with the OAuth2 Provider,
#        # we'll be generating an auth token for the user and sending the token to the
#        # redirectUri mentioned by the client in the /oauth2/authorize request.
#        # We're not using cookies because they won't work well in mobile clients.
#        authorizedRedirectUris:
#            - https://ecm-eat-clean-menu.azurewebsites.net/api/v1/auth/login